# Generated by Django 3.2.3 on 2021-10-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.manager'),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.department'),
        ),
    ]
