# Generated by Django 3.2.3 on 2021-09-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='password',
        ),
    ]
