# Generated by Django 3.2.3 on 2021-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_management_app', '0002_auto_20211004_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
