# Generated by Django 3.2.3 on 2021-09-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_management_app', '0002_auto_20210923_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default=1, max_length=8)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise_management_app.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
